WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        private EfDbContext db = new EfDbContext();
        public int PageSize = 9;

        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = db.Products
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(p => p.ProductId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null
                        ? db.Products.Count()
                        : db.Products.Count(e => e.Category == category)
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product product = db.Products
                .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

WebUI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Entities;

namespace WebUI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private EfDbContext db = new EfDbContext();

        public ViewResult Index()
        {
            return View(db.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product product = db.Products
                .FirstOrDefault(p => p.ProductId == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                if (product.ProductId == 0)
                {
                    db.Entry(product).State= EntityState.Added;
                    db.SaveChanges();
                    return Redirect("~/");
                }
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = $"Изменения в товаре \"{product.Name}\" были сохранены";
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        public void Save(Product product)
        {
            if (product.ProductId == 0)
            {
                db.Products.Add(product);
            }
            else
            {
                Product dbEntry = db.Products.Find(product.ProductId);
                if (dbEntry != null)
                {
                    dbEntry.Name = product.Name;
                    dbEntry.Description = product.Description;
                    dbEntry.Price = product.Price;
                    dbEntry.Category = product.Category;
                    dbEntry.ImageData = product.ImageData;
                    dbEntry.ImageMimeType = product.ImageMimeType;
                }
            }
            db.SaveChanges();
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpGet]
        public ActionResult Delete(int? productId)
        {
            if (productId == null)
            {
                return HttpNotFound();
            }
            Product product = db.Products.Find(productId);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? productId)
        {
            if (productId == null)
            {
                return HttpNotFound();
            }
            Product product = db.Products.Find(productId);
            if (product == null)
            {
                return HttpNotFound();
            }
            db.Products.Remove(product);
            db.SaveChanges();
            TempData["message"] = $"Товар \"{product.Name}\" успешно удален";
            return RedirectToAction("Index");
        }
    }
}

WebUI/Views/User/Edit.cshtml
@model Domain.Entities.Product

@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = false;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}

<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование товара «@Model.Name»</h3>
    </div>

    @using (Html.BeginForm("Edit", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                    switch (property.PropertyName)
                    {
                        case "ProductId":
                        case "ImageData":
                        case "ImageMimeType":
                            break;
                        default:
                            <div class="form-group">
                                <label>@(property.DisplayName ?? property.PropertyName)</label>
                                @if (property.PropertyName == "Description")
                                {
                                    @Html.TextArea(property.PropertyName, null,
                                        new { @class = "form-control", rows = 5 })
                                }
                                else
                                {
                                    @Html.TextBox(property.PropertyName, null,
                                        new { @class = "form-control" })
                                }
                                @Html.ValidationMessage(property.PropertyName)
                            </div>
                            break;
                    }

                }
                <div class="form-group">
                    <div style="position: relative">
                        <label>Картинка товара</label>
                        <a class="btn" href="javascript:">
                            Выберите файл...
                            <input type="file" name="Image" size="40"
                                   style="position: absolute; z-index: 2; top: 0; left: 0; filter: alpha(opacity = 0); opacity: 0; background-color: transparent; color: transparent" onchange='$("#upload").html($(this).val())'/>
                        </a>
                        <span class="label label-info" id="upload"></span>
                    </div>
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">Нет картинки</div>
                    }
                    else
                    {
                        <img class="img-thumbnail" width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.ProductId })"/>
                    }
                </div>

        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
       {
           @class = "btn btn-default"
       })
        </div>
    }
</div>

WebUI/Views/User/Index.cshtml
@model IEnumerable<Domain.Entities.Product>

@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список товара</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Название</th>
                <th class="text-right">Цена</th>
                <th class="text-center">Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ProductId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductId })</td>
                    <td class="text-right">@item.Price.ToString("F") руб</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "User"))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("ProductId", item.ProductId)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Удалить" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить товар", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>